<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */

use App\Apartment;
use Faker\Generator as Faker;

$nextIndex = nextApartment();
$factory->define(Apartment::class, function (Faker $faker) use ($nextIndex) {

    $apartments = [
            // ROMA
        [
            'title' => 'Jackie’s Apartments',
            'description' => 'Splendido appartamento finemente arredato con vista panoramica sul mare, 1 camera da letto, 1 soppalco (letto matrimoniale). Soggiorno con camino, TV, cassaforte, cucina, doccia/WC e terrazza privata, WiFi gratuito. Pulizie giornaliere.',
            'number_rooms' => 1,
            'number_toiletes' => 1,
            'number_beds' => 1,
            'area' => 80,
            'address' => 'VIA FILIPPO TURATI 62-64, 00185 ROMA',
            'cover_image' => '',
        ],
        [
            'title' => 'Appartamento in Lucina',
            'description' => "Situato a Roma, a 600 m dalla Fontana di Trevi e a 1,2 km da Piazza di Spagna, l'Appartamento in Lucina offre camere con aria condizionata e bagno privato. La struttura si trova vicino a Largo di Torre Argentina, al Pantheon e a Piazza di Spagna. Avrete a disposizione una cucina in comune e la connessione WiFi gratuita in tutte le aree.",
            'number_rooms' => 2,
            'number_toiletes' => 1,
            'number_beds' => 2,
            'area' => 75,
            'address' => 'Via in Lucina, 10, 00186 Roma RM',
            'cover_image' => '',
        ],
        [
            'title' => 'Light Charme Casa Vacanze',
            'description' => "Light Charme è un appartamento a soli 1 km dal Palazzo del Quirinale. Questo appartamento si trova a 10 minuti a piedi dalla Scalinata di Trinità dei Monti. Il centro di Roma dista 3 km dalla struttura. I diversi ristoranti, tra cui i Sapori D'Ischia e l'Orlando, distano 50 metri dall'appartamento Light Charme. Una breve passeggiata dall'appartamento vi porterà al Museo e alla Cripta dei Frati Cappuccini. L'aeroporto di Roma Ciampino dista 15 km da questo alloggio.",
            'number_rooms' => 2,
            'number_toiletes' => 2,
            'number_beds' => 2,
            'area' => 98,
            'address' => 'Via Sicilia, 50, 00187 Roma RM',
            'cover_image' => '',
        ],
        [
            'title' => 'Casa Art Apartment',
            'description' => "Appartamento di 55 mq situato al piano terra in un moderno edificio residenziale dotato di servizio di portineria e videosorveglianza. Soggiorno spazioso con nuovissima cucina dotata di tutti i comfort. Si accede alla zona notte tramite un disimpegno che divide la camera da letto dal bagno. L'ambiente è dotato di climatizzatori, riscaldamento a pavimento,TV, Wi-Fi, Netflix. Ampio Terrazzo.",
            'number_rooms' => 1,
            'number_toiletes' => 2,
            'number_beds' => 1,
            'area' => 55,
            'address' => 'Via di Casal Bertone, 66, 00159 Roma RM',
            'cover_image' => '',
        ],
        [
            'title' => 'Rossanella house',
            'description' => "La casa vacanze 'Rossanella House' di Roma Appio è in una zona ottimamente fornita di attività e servizi quali supermercati, ristoranti, pizzerie, bar, fast-food, gelaterie ed un centro commerciale. E' inoltre ben collegata dai mezzi di trasporto: linea bus ATAC '85' per il centro storico proprio sotto casa, metropolitana linea A fermata Colli Albani con la quale si arriva direttamente alla Stazione Termini ed in centro storico.",
            'number_rooms' => 2,
            'number_toiletes' => 2,
            'number_beds' => 2,
            'area' => 100,
            'address' => 'Via Manlio Torquato, 12, 00181 Roma RM',
            'cover_image' => '',
        ],
        [
            'title' => 'Casa Vacanze Vespucci',
            'description' => "Situato a Roma, a 1,6 km dal Foro Romano, l'Apartment Vespucci offre una sistemazione con WiFi gratuito e salotto e cucina comuni. L'alloggio è climatizzato e sorge a 1,6 km dalla Sinagoga di Roma.",
            'number_rooms' => 2,
            'number_toiletes' => 2,
            'number_beds' => 2,
            'area' => 96,
            'address' => 'Via Amerigo Vespucci, 24, 00153 Roma RM',
            'cover_image' => '',
        ],
        [
            'title' => 'Il Soffio- Casa Vacanze',
            'description' => "La posizione strategica dell'appartamento Il Soffio, permette agli ospiti di raggiungere le vicine e bellissime falesie a piedi, oppure di avventurarsi in sentieri trekking e bike, lasciando così la propria auto nel parcheggio riservato e gratuito. L'appartamento Il Soffio dispone di una moderna e spaziosa cucina attrezzata, 1 camera matrimoniale, divano letto in soggiorno, 1 ampio bagno ed una splendida e soleggiata terrazza con vista castello di Arco.",
            'number_rooms' => 2,
            'number_toiletes' => 1,
            'number_beds' => 3,
            'area' => 85,
            'address' => 'Viale dei Quattro Venti, 97, 00152 Roma RM',
            'cover_image' => '',
        ],
        [
            'title' => 'Roma Blue Apartment',
            'description' => "Una dimora molto accogliente in un quartiere ricco di storia, tranquillo e immerso in un'atmosfera autentica. In poche ore ti senti nel cuore di Roma, a pochi passi da monumenti che tolgono il fiato. La casa ha tutte le comodità, è pulita, luminosa e molto allegra!",
            'number_rooms' => 3,
            'number_toiletes' => 2,
            'number_beds' => 3,
            'area' => 105,
            'address' => 'Via del Lago Terrione, 83, 00165 Roma RM',
            'cover_image' => '',
        ],
        [
            'title' => 'San Pietro Orange',
            'description' => "Delizioso appartamento di 45 mq situato nel rione storico di Roma Borgo Pio a 500 metri da San Pietro. Spazioso e finemente accessoriato, con soppalco artigianale per una confortevole area relax o lettura. Cucina e bagno. Primo piano senza ascensore.",
            'number_rooms' => 2,
            'number_toiletes' => 2,
            'number_beds' => 3,
            'area' => 110,
            'address' => 'Piazza Americo Capponi, 3, 00193 Roma RM',
            'cover_image' => '',
        ],
        [
            'title' => 'Trastevere Suite',
            'description' => "La Suite Dotata di ogni comfort e ristrutturata nell'ottobre 2015, essa ha come obiettivo principale quello di ricreare un ambiente raffinato,  elegante e allo stesso tempo accogliente, che non ha nulla da invidiare ad una camera d’albergo a 4 stelle.",
            'number_rooms' => 3,
            'number_toiletes' => 3,
            'number_beds' => 3,
            'area' => 99,
            'address' => 'Via del Mattonato, 6, 00153 Roma RM',
            'cover_image' => '',
        ],

        // MILANO

        [
            'title' => 'Via Savona',
            'description' => "Appartamento confortevole, accogliente e luminoso. Zona tranquilla, 10 minuti a piedi dal Museo delle Culture MUDEC, 15 minuti di tram (linea 14) da Porta Genova/Navigli e 20 minuti circa dal Duomo. Fermata filobus 90/91 P.za Napoli nelle vicinanze. Camera da letto arredata con scrivania, letto matrimoniale e singolo. Cucina abitabile fornita di mobili, lavatrice e tutti gli accessori. Bagno con vasca/doccia. Appartamento al 3° piano con ascensore. Disponibile per l'intero vostro soggiorno.",
            'number_rooms' => 2,
            'number_toiletes' =>1,
            'number_beds' => 2,
            'area' => 200,
            'address' => 'Via Rutilia 6, Ripamonti Corvetto, Milano',
            'cover_image' => '',
        ],
        [
            'title' => 'Design District',
            'description' => "Affittasi stanza privata in appartamento grande e luminoso in zona Isola, Milano. La casa è completamente arredata ed è composta da: sala, cucina, 2 camere da letto, bagno e balconcino. Lo stabile si trova vicino alle metro Maciachini (gialla) / Pta. Garibaldi (verde) / Isola (Llilla). Sotto casa si trovano diverse fermate tram (4 e 2) con direzione Duomo e la posizione è molto favorevole per muoversi in ogni zona della città. Stazione centrale a soli 10 min di distanza.",
            'number_rooms' => 1,
            'number_toiletes' => 1,
            'number_beds' => 1,
            'area' => 100,
            'address' => ' Corso Magenta 61, Milano Centro, Milano',
            'cover_image' => '',
        ],
        [
            'title' => 'NOLO',
            'description' => "Ampio monolocale in Nolo. Libero per lunghi e corti periodi. Molto silenzioso. AC. Terrazza. Veramente molto carino. I letti possono essere uniti a formare un matrimoniale.",
            'number_rooms' => 1,
            'number_toiletes' => 1,
            'number_beds' => 2,
            'area' => 150,
            'address' => 'Via Zuretti 46, Stazione Centrale, Milano',
            'cover_image' => '',
        ],
        [
            'title' => 'DUOMO12 - La Suite',
            'description' => "Soggiornare a pochi passi dal Duomo di Milano, cattedrale simbolo della città e uno dei monumenti più belli e suggestivi al mondo in appartamenti di ricercato design, completi di tutte le comodità possibili per rendere il vostro soggiorno speciale e vivere un sogno a occhi aperti.",
            'number_rooms' => 1,
            'number_toiletes' => 1,
            'number_beds' => 2,
            'area' => 200,
            'address' => 'Via Benedetto Marcello 47, Stazione Centrale, Milano',
            'cover_image' => '',
        ],
        [
            'title' => 'Schiapparelli A Flat',
            'description' => "Appartamento su due livelli dotato gli ogni comfort (aria condizionata, riscaldamento, collegamento WiFi in fibra ottica, TV) a pochi passi dalla Stazione Centrale in una zona ricca di ristoranti e servizi. I terminal delle navette per gli aeroporti di Linate, Malpensa ed Orio sono a meno di 5 minuti a piedi!",
            'number_rooms' => 2,
            'number_toiletes' => 2,
            'number_beds' => 2,
            'area' => 189,
            'address' => ' Corso Monforte 27, Milano Centro, Milano',
            'cover_image' => '',
        ],
        [
            'title' => 'La Mia Terrazza su Milano',
            'description' => "Splendido appartamento con terrazza a 3 minuti dalla metro e 15 minuti dal centro. La stazione centrale è a 15/20 minuti a piedi e il tram sotto casa porta direttamente davanti al teatro La Scala. Il quartiere è pieno di supermercati e negozi.",
            'number_rooms' => 2,
            'number_toiletes' => 1,
            'number_beds' => 2,
            'area' => 300,
            'address' => ' Via Messina 38, Sempione, Milano',
            'cover_image' => '',
        ],
        [
            'title' => 'Casa Mec',
            'description' => "Appartamento al piano terra, recentemente ristrutturato, completamente arredato e dotato di tutti i confort (lavatrice, biancheria casa, TV, macchina del caffè, Asciugacapelli, Wifii…) Perfetta sia per Visitare la città di Milano sia per viaggi di lavoro.",
            'number_rooms' => 3,
            'number_toiletes' => 2,
            'number_beds' => 2,
            'area' => 180,
            'address' => 'Via Venezia Giulia 8, Milano',
            'cover_image' => '',
        ],
        [
            'title' => 'Zuretti casa',
            'description' => "Appartamento molto accogliente sito al quarto piano in stabile del'900 e così composto: ingresso con soggiorno e divano letto, cucina, bagno e camera matrimoniale.",
            'number_rooms' => 4,
            'number_toiletes' => 2,
            'number_beds' => 2,
            'area' => 180,
            'address' => 'Via Vittorio Scialoia 3, Niguarda, Milano',
            'cover_image' => '',
        ],
        [
            'title' => 'Insustrial Apartment Duomo',
            'description' => "L'appartamento è dotato di tutto ciò che vi servirà per trascorre un perfetto soggiorno milanese. A due passi dal fuori salone di Lambrate e a pochi metri dalla metropolitana. La posizione è perfetta per tutti quegli ospiti che vogliono rilassarsi in uno dei quartieri più dinamici della città.",
            'number_rooms' => 1,
            'number_toiletes' => 2,
            'number_beds' => 1,
            'area' => 140,
            'address' => 'Via Giovanni Antonio Plana 33, Certosa, Milano',
            'cover_image' => '',
        ],
        [
            'title' => 'Amazing Studio',
            'description' => " Tranquillo, affacciato su grazioso cortile interno. Camera con letto matrimoniale e letto singolo aggiuntivo, divanoletto x2 nel salottino. Piccola cucina completa con frigo, forno microonde e stoviglie.",
            'number_rooms' => 4,
            'number_toiletes' => 1,
            'number_beds' => 4,
            'area' => 100,
            'address' => 'Via Europa 56, Cologno Monzese, Milano',
            'cover_image' => '',
        ],
        [
            'title' => 'Suite private',
            'description' => "Appartamento dal design moderno in una delle zone più esclusive di Milano, Porta Venezia: ricca di locali, ristoranti e negozi. Luminosissimo, può ospitare fino a 4 persone grazie al divano letto in soggiorno.",
            'number_rooms' => 4,
            'number_toiletes' => 4,
            'number_beds' => 2,
            'area' => 180,
            'address' => 'Via Fratelli Cervi, Milano',
            'cover_image' => '',
        ],
        [
            'title' => 'Su Porta Venezia',
            'description' => "Un sofisticato e nuovo appartamento milanese. Ideale per viaggiatori d'affari, coppie, piccole famiglie o singoli. C'è qualcosa per tutti in questo fantastico appartamento e quartiere.",
            'number_rooms' => 2,
            'number_toiletes' => 1,
            'number_beds' => 2,
            'area' => 120,
            'address' => 'Via Mazzini 3, Cernusco sul Naviglio, Milano',
            'cover_image' => '',
        ],
        [
            'title' => 'Calliope',
            'description' => "Casa intera tutta per te – Impegno per una pulizia avanzata",
            'number_rooms' => 1,
            'number_toiletes' => 1,
            'number_beds' => 1,
            'area' => 100,
            'address' => 'Via Circonvallazione Idro 3, Milano',
            'cover_image' => '',
        ],

        // TORINO
        
        [
            'title' => 'Eco Art',
            'description' => "Dotato di ogni confort, Servizio bici del Comune di Torino (TOBIKE)di fronte a casa.A 200 mt dalla metro e 400 mt da stazione treni (Porta Susa).",
            'number_rooms' => 1,
            'number_toiletes' => 2,
            'number_beds' => 1,
            'area' => 120,
            'address' => "Via Principi D'Acaja 17, Milano",
            'cover_image' => '',
        ],
        [
            'title' => 'Casa Bogo Nuova',
            'description' => "Intero appartamento da poco ristrutturato con l'intento di farvi sentire a casa vostra. Adatto sia per una coppia che cerca la massima discrezione e privacy, che per una famiglia che vuole comfort e funzionalità.",
            'number_rooms' => 2,
            'number_toiletes' => 1,
            'number_beds' => 1,
            'area' => 120,
            'address' => 'Corso Duca Degli Abruzzi 94, Crocetta, Torino',
            'cover_image' => '',
        ],
        [
            'title' => 'Monolocale Indipendente',
            'description' => "In un edificio storico a due minuti da Piazza Vittorio, Via Po, Piazza Castello, la Mole Antonelliana, la Gran Madre si trova questo piccolo graziosissimo monolocale. Elegante e pratico, dotato di tutti i comfort, è finemente ristrutturato ed arredato a nuovo",
            'number_rooms' => 3,
            'number_toiletes' => 2,
            'number_beds' => 2,
            'area' => 100,
            'address' => 'Via Spalato 7, Torino',
            'cover_image' => '',
        ],
        [
            'title' => 'Le Petite',
            'description' => "L'appartamento ha spazi ampi molta luce e la presenza di supermercati, bar, tabacchi, diverse trattorie, una farmacia e spazi verdi nello stesso isolato. Ci vivo felicemente e sono altrettanto felice di cederlo a chi voglia godersi questa splendida città",
            'number_rooms' => 4,
            'number_toiletes' => 2,
            'number_beds' => 2,
            'area' => 200,
            'address' => 'Via Principe Amedeo 41 Bis, Centro Storico di Torino, Torino',
            'cover_image' => '',
        ],
        [
            'title' => 'Mole Sweet Studio',
            'description' => "Attico mansardato con soffitti alti, si trova al quarto ed ultimo piano, raggiungibile con un ampio e comodo ascensore.Ha 5 camere da letto. Nel soggiorno vi è un divano letto matrimoniale ed un letto a barchetta singolo.",
            'number_rooms' => 5,
            'number_toiletes' => 2,
            'number_beds' => 2,
            'area' => 180,
            'address' => 'Via Borgo Dora 36, Aurora Vanchiglia, Torino',
            'cover_image' => '',
        ],
        [
            'title' => 'Klimt House',
            'description' => "La stanza è confortevole. Ad accoglierti in casa Ci sono 2 gatti meravigliosi e coccolosi. E si trova a pochissimi passi da porta nuova.",
            'number_rooms' => 3,
            'number_toiletes' => 1,
            'number_beds' => 2,
            'area' => 180,
            'address' => 'Corso Grosseto 366/7, Torino',
            'cover_image' => '',
        ],
        [
            'title' => 'Happy Day',
            'description' => "Splendido e luminoso appartamento mansardato sito in pieno centro in casa del ‘700, dotato di terrazzo e abbaino con vista sui tetti e il cielo, bagno con doccia idromassaggio, parquet, 2 TV (una dotata di Google ChromeCast= Smart Tv) e cucina attrezzata. Situato nella zona pedonale, ricca di locali e servizi.",
            'number_rooms' => 2,
            'number_toiletes' => 1,
            'number_beds' => 1,
            'area' => 100,
            'address' => 'Piazza Derna 238, Torino',
            'cover_image' => '',
        ],
        [
            'title' => 'Pop Apartment',
            'description' => "Alloggio comodo al centro e alla linea ferroviaria per aeroporto e Venaria Reale, nelle vecinanze ci sono tutti i tipi di negozi e supermercati oltre ad un mercato rionale che si svolge tutte le mattine a al sabato tutto il giorno",
            'number_rooms' => 1,
            'number_toiletes' => 1,
            'number_beds' => 1,
            'area' => 100,
            'address' => 'Via Nazioni Unite 11, Collegno, Torino',
            'cover_image' => '',
        ],
        [
            'title' => 'Dora maison',
            'description' => "Appartamento comodo ai mezzi pubblici per raggiungere il centro città (tram sotto casa), 10 minuti a piedi per arrivare allo Juventus Stadium, facilità per la Reggia di Venaria.",
            'number_rooms' => 3,
            'number_toiletes' => 2,
            'number_beds' => 2,
            'area' => 160,
            'address' => 'Via Paolo Gaidano 113, Mirafiori, Torino',
            'cover_image' => '',
        ],
        [
            'title' => 'B&B Torino',
            'description' => "La casa è arredata in stile moderno è disposta su 3 Piani.",
            'number_rooms' => 4,
            'number_toiletes' => 1,
            'number_beds' => 2,
            'area' => 160,
            'address' => 'Piazza Galimberti 12, Lingotto, Torino',
            'cover_image' => '',
        ],
        [
            'title' => 'Barolo Wine Loft',
            'description' => "L’appartamento è ubicato in un palazzo d’epoca ed è finemente ristrutturato, ideale per famiglie e per lunghi soggiorni. Situato in un quartiere tranquillo. Comodo per raggiungere i più importanti musei della città e l’università. Ideale per visitare la città a piedi.",
            'number_rooms' => 3,
            'number_toiletes' => 2,
            'number_beds' => 2,
            'area' => 130,
            'address' => 'Via Pracavallo 3, Nichelino,, Torino',
            'cover_image' => '',
        ],
        [
            'title' => 'Tip Top Torino',
            'description' => "Elegante e pratico, dotato di tutti i comfort, è finemente ristrutturato ed arredato a nuovo. Un grazioso balconcino in pietra originale che si affaccia sul cortile interno ed una bella finestra aprono la vista al fiume Po",
            'number_rooms' => 2,
            'number_toiletes' => 1,
            'number_beds' => 1,
            'area' => 110,
            'address' => 'Via Santa Andrea 20 Garino Vinovo, Candiolo, Torino',
            'cover_image' => '',
        ],
        [
            'title' => 'Santa Rota',
            'description' => "Appartamento piccolo ma funzionale, cucina dotata di tutto e terrazzo dove poter fare un aperitivo, a 2 km dal centro e 2 km dal maria pia hospital, ottimo rapporto qualità/prezzo",
            'number_rooms' => 1,
            'number_toiletes' => 1,
            'number_beds' => 1,
            'area' => 100,
            'address' => 'Corso Giulio Cesare 338/34, Torino',
            'cover_image' => '',
        ],
        [
            'title' => 'Casa Baciu',
            'description' => "intero Appartamento ben arredato e fornito di tutti i comfort. Stanza con letto 1.1/2 più bagno .4' piano con ascensore.Taxi e servizi pubblici sotto casa.",
            'number_rooms' => 2,
            'number_toiletes' => 1,
            'number_beds' => 1,
            'area' => 120,
            'address' => 'Via Roma 36, San Mauro Torinese, Torino',
            'cover_image' => '',
        ],

        // VERONA

        [
            'title' => 'Lovely House',
            'description' => "Alimentata da energia elettrica, auto prodotta dai pannelli solari, gode di tutti gli ultimi sistemi tecnologicamente avanzati in tema di sicurezza e comfort abitativo.",
            'number_rooms' => 3,
            'number_toiletes' => 1,
            'number_beds' => 2,
            'area' => 150,
            'address' => 'Corso Porta Nuova 39, Centro storico di Verona, Verona',
            'cover_image' => '',
        ],
        [
            'title' => 'Il Girasole',
            'description' => "Deliziosa e confortevole camera con bagno, interamente ristrutturata, silenziosa, climatizzata con riscaldamento e aria condizionata, nel pieno centro della città, a due passi da Porta Borsari e da tutte le attrazioni turistiche di Verona. Fantastico per una coppia, comodamente abitabile fino ad un massimo di 2 ospiti.",
            'number_rooms' => 2,
            'number_toiletes' => 2,
            'number_beds' => 2,
            'area' => 100,
            'address' => 'Via Luigi Lenotti 4/C-E, San Zeno, Verona',
            'cover_image' => '',
        ],
        [
            'title' => 'Giulietta',
            'description' => "La Suite Gialla dispone di entrata indipendente, cucina privata, bagno privato, tv, aria condizionata, wifi gratis, giardino, terrazza panoramica.",
            'number_rooms' => 1,
            'number_toiletes' => 1,
            'number_beds' => 1,
            'area' => 80,
            'address' => 'Via san Vitale 12, Verona',
            'cover_image' => '',
        ],
        [
            'title' => 'DoubleRoom',
            'description' => "Il mio alloggio è vicino all'Arena, nel centro storico della città, splendide viste panoramiche, arte e cultura a pochi passi, parchi verdi.",
            'number_rooms' => 3,
            'number_toiletes' => 2,
            'number_beds' => 2,
            'area' => 130,
            'address' => 'Via G.Grioli 2c, Centro storico di Verona, Verona',
            'cover_image' => '',
        ],
        [
            'title' => 'Attico a Verona',
            'description' => "Moderno e accogliente appartamento di 45 mq, in grado di ospitare fino a 4 persone, situato al secondo piano di un bellissimo palazzo d'epoca ristrutturato.",
            'number_rooms' => 4,
            'number_toiletes' => 1,
            'number_beds' => 2,
            'area' => 100,
            'address' => 'Via Carlo Belviglieri 42, Borgo Venezia, Verona',
            'cover_image' => '',
        ],
        [
            'title' => 'Casa Sottoriva',
            'description' => "Casa intera tutta per te, impegno per una pulizia avanzata",
            'number_rooms' => 5,
            'number_toiletes' => 2,
            'number_beds' => 3,
            'area' => 200,
            'address' => 'Via Centro 23, Borgo Roma, Verona',
            'cover_image' => '',
        ],
        [
            'title' => 'Palazzo Negri',
            'description' => "Nel quartiere Stadio in strategica posizione A 500 metri dalla Stazione dei treni e a 1,5 km dal centro , in strada defilata dalle principali vie , in piccolo condominio al 2° ed ultimo piano (senza ascensore)si trova il Vasari Apartment un vero accogliente e riservato appartamento di ben 90 mt quadrati .",
            'number_rooms' => 1,
            'number_toiletes' => 1,
            'number_beds' => 1,
            'area' => 100,
            'address' => 'Via Scuderlando 40, Borgo Roma, Verona',
            'cover_image' => '',
        ],
        [
            'title' => 'Da Aurora',
            'description' => "A vostra disposizione il servizio gratuito di biciclette che vi permetterà di visitare comodamente il centro storico della città. La struttura, dotata di giardini interni offre inoltre per chi lo desidera parcheggio gratuito dell’ auto.",
            'number_rooms' => 2,
            'number_toiletes' => 2,
            'number_beds' => 2,
            'area' => 160,
            'address' => 'Via Campagnol Di Tombetta 77, Borgo Roma, Verona',
            'cover_image' => '',
        ],
        [
            'title' => "Ca' delle Cornacchie",
            'description' => "Si trova a 2 km dal pieno centro città di Verona, raggiungibile con autobus che fermano a 30 metri dall'appartamento ben collegati con la stazione e le zone principali di Verona.",
            'number_rooms' => 3,
            'number_toiletes' => 1,
            'number_beds' => 2,
            'area' => 170,
            'address' => 'Via Legnago 135, Borgo Roma, Verona',
            'cover_image' => '',
        ],
        [
            'title' => 'Cavour44',
            'description' => "Appartamento in splendido casale con giardino privato.",
            'number_rooms' => 2,
            'number_toiletes' => 1,
            'number_beds' => 2,
            'area' => 140,
            'address' => 'Via Santa Teresa 3, Borgo Roma, Verona',
            'cover_image' => '',
        ],
        [
            'title' => 'Attico Arena',
            'description' => "Accogliente appartamento situato nel cuore di Verona. L'appartamento è stato recentemente ristrutturato da una ditta di architetti specializzati nello sviluppo di appartamenti 'boutique', è completamente arredato e tutti i mobili, la cucina e gli elettrodomestici (TV a schermo piatto, lavatrice/asciugatrice, lavastoviglie ecc.) sono nuovi.",
            'number_rooms' => 4,
            'number_toiletes' => 2,
            'number_beds' => 2,
            'area' => 190,
            'address' => 'Via Valerio Catullo 1, Centro storico di Verona, Verona',
            'cover_image' => '',
        ],
        [
            'title' => 'Gardenia Aparment',
            'description' => "La camera matrimoniale dispone di un bagno adiacente ad uso esclusivamente privato. Il tutto completo di accessori e gli spazi comuni usufruibili.",
            'number_rooms' => 1,
            'number_toiletes' => 1,
            'number_beds' => 1,
            'area' => 120,
            'address' => 'Via Ponte Pietra 3, Centro storico di Verona, Verona',
            'cover_image' => '',
        ],
        [
            'title' => 'Diamond Suite',
            'description' => "Appartamento appena ristrutturato ed arredato con cura al 3° piano di un palazzo signorile con ascensore. Il centro storico e l'Arena di Verona sono raggiungibili a piedi con una breve passeggiata di 10 minuti.",
            'number_rooms' => 1,
            'number_toiletes' => 1,
            'number_beds' => 1,
            'area' => 100,
            'address' => 'Via San Giovanni In Valle 14/a, Verona',
            'cover_image' => '',
        ],

        // BOLOGNA

        [
            'title' => 'Borgo San Pietro',
            'description' => "Accogliente appartamento open space con terrazza ad asola riparata dal sole. In un silenzioso interno con affacci nel verde. Tra l'ospedale Sant'Orsola, Villa Laura e l'Ospedale Bellaria, a meno di 2 km da Porta Maggiore. Parcheggio interno secondo disponibilità.",
            'number_rooms' => 3,
            'number_toiletes' => 1,
            'number_beds' => 2,
            'area' => 130,
            'address' => 'Via Saragozza 95, Saragozza, Bologna',
            'cover_image' => '',
        ],
        [
            'title' => 'Zio Totò',
            'description' => "Ampio e confortevole bilocale totalmente restaurato situato in via Borgo di San Pietro, 4, nel pieno Centro Storico di Bologna. A Pochi passi dall'università. Ingresso nella zona living, pavimenti in parquet, divano e angolo cottura dotato di tutti gli utensili per la casa. La zona notte è fornita di un letto matrimoniale molto comodo ed in letto singolo.",
            'number_rooms' => 2,
            'number_toiletes' => 1,
            'number_beds' => 1,
            'area' => 120,
            'address' => 'Via Saffi 16, Bologna',
            'cover_image' => '',
        ],
        [
            'title' => 'il Teatro',
            'description' => "Moderno e accogliente loft di circa 100 mq disposto su due livelli e sito al pianterreno di un elegante palazzo del centro storico di Bologna, casa natale del pittore Morandi.",
            'number_rooms' => 3,
            'number_toiletes' => 1,
            'number_beds' => 2,
            'area' => 100,
            'address' => 'Via Mascarella 102, Bologna',
            'cover_image' => '',
        ],
        [
            'title' => 'Il Giardino Nascosto',
            'description' => "Bilocale nuovo, luminoso, grazioso, arredato con gusto e accogliente, situato in una strada tranquilla e silenziosa. Parcheggio auto privato a pagamento. Le pulizie sono effettuate seguendo il protocollo avanzato di pulizia di Boolb&b, sviluppato sotto la guida di esperti del settore.",
            'number_rooms' => 2,
            'number_toiletes' => 2,
            'number_beds' => 1,
            'area' => 200,
            'address' => 'Strada Maggiore 79, Savena, Bologna',
            'cover_image' => '',
        ],
        [
            'title' => 'Tra le 2 Torri',
            'description' => "Bellissima ed ampia camera matrimoniale con soffitto alto, soggiorno con angolo cottura luminoso con divano letto in pelle a una piazza a mezzo.",
            'number_rooms' => 1,
            'number_toiletes' => 1,
            'number_beds' => 1,
            'area' => 180,
            'address' => 'Via Sebastiano Serlio 28, Bologna',
            'cover_image' => '',
        ],
        [
            'title' => 'Caduti del Lavoro',
            'description' => "Appartamento al 3°piano molto luminoso e tranquillo grazie anche alla posizione centrale del condominio. Posizione strategica per la vicinanza al centro (Università e Ospedale Sant'Orsola) alla Fiera e a FICO e per la viabilità verso la tangenziale/autostrada, grazie allo svincolo della Fiera a breve distanza.",
            'number_rooms' => 5,
            'number_toiletes' => 2,
            'number_beds' => 3,
            'area' => 210,
            'address' => 'Viale Felsina 49, Savena, Bologna',
            'cover_image' => '',
        ],
        [
            'title' => 'Il tuo spazio a Bologna',
            'description' => "Raffinato ed elegante trilocale con ampio balcone, sito al 3° piano (ascensore) di un moderno complesso residenziale dotato di portineria, posto auto e piscina condominiale, a poca distanza dal centro storico della città.",
            'number_rooms' => 3,
            'number_toiletes' => 1,
            'number_beds' => 3,
            'area' => 120,
            'address' => 'Piazza San Francesco 6, Saragozza, Bologna',
            'cover_image' => '',
        ],
        [
            'title' => 'La Lanterna',
            'description' => "Accogliente open space di 170 mq su due livelli recentemente ristrutturato in centro a Bologna. In zona centrale ma silenziosa, a 950 metri dal centro storico e a 750 metri dalla stazione ferroviaria. Nelle immediate vicinanze 3 supermercati, numerosi bar e ristoranti.",
            'number_rooms' => 4,
            'number_toiletes' => 1,
            'number_beds' => 4,
            'area' => 170,
            'address' => 'Via don Minzoni 4, Bologna',
            'cover_image' => '',
        ],
        [
            'title' => 'Santo Stefano',
            'description' => "Accogliente appartamento in un quartiere residenziale immerso nel verde e vicino a un parco. Di facile accesso dall'autostrada e a pochi minuti dalla Fiera e dal nuovo parco agroalimentare FICO. A 15 minuti di Autobus dal centro storico. Molto vicino all'Ospedale Bellaria, Villa Laura e all'Ospedale Sant'Orsola.",
            'number_rooms' => 3,
            'number_toiletes' => 2,
            'number_beds' => 3,
            'area' => 135,
            'address' => 'Via Nosadella 19 , Saragozza, Bologna',
            'cover_image' => '',
        ],
        [
            'title' => 'Zambini House',
            'description' => "La stanza si trova all'interno di un appartamento cui si accede dal cortile privato incorniciato da un po di verde. La camera da letto, con letto matrimoniale, si trova al piano terra, subito dopo la porta di ingresso all'appartamento. Il bagno è adiacente alla camera da letto e ad uso esclusivo.",
            'number_rooms' => 2,
            'number_toiletes' => 2,
            'number_beds' => 2,
            'area' => 154,
            'address' => 'Via Borgonuovo 2, Bologna',
            'cover_image' => '',
        ],
        [
            'title' => 'Lady Room',
            'description' => "Il monolocale di recente ristrutturazione è situato al quarto piano di un palazzo munito di ascensore. Perfetto per coppie o viaggiatori singoli.",
            'number_rooms' => 1,
            'number_toiletes' => 1,
            'number_beds' => 1,
            'area' => 169,
            'address' => 'Via Fratelli Rosselli 14, Bologna',
            'cover_image' => '',
        ],
        [
            'title' => 'Da Lucio',
            'description' => "Intero ampio e comodo appartamento in zona tranquilla e nel verde, ideale per rilassarsi. Posizione ottimale per raggiungere la Fiera, il Parco Nord, Villa Erbosa, Zona Fico e il centro città. Ingresso indipendente. Appena ristrutturato è ideale per soggiorni di lavoro, studio e vacanze.",
            'number_rooms' => 2,
            'number_toiletes' => 1,
            'number_beds' => 2,
            'area' => 180,
            'address' => 'Via Larga, 4, Bologna',
            'cover_image' => '',
        ],
        [
            'title' => 'Pignoletto House',
            'description' => "Ampia Camera singola luminosa in una casa privata. Entrata privata ma senza possibilità di parcheggio interno. Nella strada il parcheggio è libero. I spazi comuni sono in condivisione con 1 coppia di giovani, Edvin e Giulia.",
            'number_rooms' => 4,
            'number_toiletes' => 2,
            'number_beds' => 4,
            'area' => 170,
            'address' => 'Via San Donato 159/161, Bologna',
            'cover_image' => '',
        ],

        // FIRENZE

        [
            'title' => 'Palma loft',
            'description' => "Appartamento nuovissimo e moderno di circa 100 mq interamente su un solo piano. Appena entrati scoprirete il modernissimo soggiorno con TV a schermo piatto, divano letto per due persone, zona pranzo con tavolo per 6 persone e cucina attrezzata .Accanto al entrata sulla destra troviamo il primo bagno con doccia cromoterapia e la prima camera matrimoniale con una piccola scrivania adatta PC.",
            'number_rooms' => 3,
            'number_toiletes' => 2,
            'number_beds' => 2,
            'area' => 100,
            'address' => 'Via della Scala 50, Santa Maria Novella, Firenze',
            'cover_image' => '',
        ],
        [
            'title' => 'Camera a Santa Croce',
            'description' => "L'appartamento dispone di un soppalco con letto matrimoniale, un salotto con divano letto matrimoniale, una cucina completa di ogni elettrodomestico ed un bagno con doccia.",
            'number_rooms' => 2,
            'number_toiletes' => 1,
            'number_beds' => 2,
            'area' => 45,
            'address' => 'Borgo Ognissanti 80, piano II, Santa Maria Novella, Firenze',
            'cover_image' => '',
        ],
        [
            'title' => 'Ponte Vecchio Apartment',
            'description' => "Bellissimo monolocale situato nel centro storico di Firenze, recentemente rinnovato e vicino a tutte le principali attrazioni, raggiungibili in massimo 10 minuti!",
            'number_rooms' => 1,
            'number_toiletes' => 1,
            'number_beds' => 1,
            'area' => 50,
            'address' => 'Via Camillo Cavour 42, San Marco - Santissima Annunziata, Firenze',
            'cover_image' => '',
        ],
        [
            'title' => 'Sui Tetti di Firenze',
            'description' => "Splendido appartamento open-space, molto luminoso, completamente ristrutturato ed arredato, dotato di ogni comfort. A due passi da Ponte Vecchio, dalla stazione di Santa Maria Novella ed a 10 minuti a piedi da Piazza del Duomo.",
            'number_rooms' => 2,
            'number_toiletes' => 1,
            'number_beds' => 1,
            'area' => 100,
            'address' => 'Via Giuseppe La Farina 27, Campo di Marte, Firenze',
            'cover_image' => '',
        ],
        [
            'title' => 'La Gabbia del Grillo',
            'description' => "Bellissimo appartamento appena rinnovato, per 3 ospiti, al primo piano , in un caratteristico palazzo della vecchia Firenze, in pieno centro storico, a soli 5 minuti da tutti i luoghi di interesse : musei, negozi, botteghe artigiane della nostra città, che per l'arte, i suoi palazzi e la sua cultura è la più bella del mondo.",
            'number_rooms' => 3,
            'number_toiletes' => 2,
            'number_beds' => 2,
            'area' => 120,
            'address' => 'Lungarno Archibusieri 8, Uffizi, Firenze',
            'cover_image' => '',
        ],
        [
            'title' => "L'anfieteatro Nascosto",
            'description' => "L'appartamento è stato completamente restaurato l'ultimo mese. Molto ben attrezzato, è composto da un'ampia camera da letto con letto matrimoniale, una cucina attrezzata, tavolo da pranzo, frigorifero, piastre elettriche, un grazioso , un bagno privato con doccia.",
            'number_rooms' => 4,
            'number_toiletes' => 1,
            'number_beds' => 4,
            'area' => 189,
            'address' => 'Via Cardinal Leopoldo 62, Firenze',
            'cover_image' => '',
        ],
        [
            'title' => 'Stanza Boccaccio',
            'description' => "Appartamento dotato di 2 camere da letto, soggiorno, TV a schermo piatto, cucina attrezzata con zona pranzo e 2 bagni con bidet e lavatrice. Per una maggiore comodità, la struttura fornisce asciugamani e lenzuola a un costo aggiuntivo.",
            'number_rooms' => 1,
            'number_toiletes' => 1,
            'number_beds' => 1,
            'area' => 50,
            'address' => 'Borgo San Jacopo 8, San Frediano, Firenze',
            'cover_image' => '',
        ],
        [
            'title' => 'Vista da Leonardo',
            'description' => "L'appartamento presenta 2 camere da letto, una TV a schermo piatto, una cucina attrezzata con lavastoviglie e forno a microonde, una lavatrice e 1 bagno con bidet. Per una maggiore comodità, la struttura fornisce asciugamani e lenzuola a un costo aggiuntivo.",
            'number_rooms' => 2,
            'number_toiletes' => 1,
            'number_beds' => 2,
            'area' => 130,
            'address' => 'Corso dei Tintori 33, Santa Croce, Firenze',
            'cover_image' => '',
        ],
        [
            'title' => 'Perla Rossa',
            'description' => "Bellissima ed ampia camera matrimoniale con soffitto alto, soggiorno con angolo cottura luminoso con divano letto in pelle a una piazza a mezzo.",
            'number_rooms' => 1,
            'number_toiletes' => 1,
            'number_beds' => 1,
            'area' => 80,
            'address' => 'Via Martelli 8, Duomo, Firenze',
            'cover_image' => '',
        ],
        [
            'title' => 'Apartment Mattonaia',
            'description' => "Situato a Firenze, a soli 1,3 km dal Mercato di Sant'Ambrogio, il Mattonaia Apartment offre una vista sulla città, la connessione WiFi gratuita e un parcheggio privato senza costi aggiuntivi. Si trova a 2,1 km da Palazzo Vecchio e offre un servizio di parcheggio e riconsegna auto.",
            'number_rooms' => 1,
            'number_toiletes' => 1,
            'number_beds' => 1,
            'area' => 95,
            'address' => 'Via Di Ripoli, 169, Firenze',
            'cover_image' => '',
        ],
        [
            'title' => 'B&B Ognissanti',
            'description' => "Descrizione da inserire",
            'number_rooms' => 2,
            'number_toiletes' => 2,
            'number_beds' => 2,
            'area' => 67,
            'address' => 'Piazza Tommaso Alva Edison 12, Campo di Marte, Firenze',
            'cover_image' => '',
        ],
        [
            'title' => 'La Camera in Fiore',
            'description' => "Descrizione da inserire",
            'number_rooms' => 3,
            'number_toiletes' => 1,
            'number_beds' => 3,
            'area' => 130,
            'address' => 'Via Del Salviatino 21, Campo di Marte, Firenze',
            'cover_image' => '',
        ],
        [
            'title' => 'Camera dei Medici',
            'description' => "Descrizione da inserire",
            'number_rooms' => 1,
            'number_toiletes' => 1,
            'number_beds' => 1,
            'area' => 89,
            'address' => 'Via dei Cioli 2, Settignano',
            'cover_image' => '',
        ],

    ];

    $i = $nextIndex->current();
    $apartment = $apartments[$i];
    // dd($apartment);
    $nextIndex->next();

    return [
        'title' => $apartment['title'],
        'description' => $apartment['description'],
        'number_rooms' => $apartment['number_rooms'],
        'number_toiletes' => $apartment['number_toiletes'],
        'number_beds' => $apartment['number_beds'],
        'area' => $apartment['area'],
        'address' => $apartment['address'],
        'cover_image' => $apartment['cover_image'],
    ];
});

function nextApartment()
{
    for($i=0; $i<76; $i++) {

        yield $i;
    }
}
